name: Rebuild automatico

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  rebuild:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
